#Compile the launch.c by linking it with the lib_simpleloader.so
launch:
	gcc -L../bin/ -m32 -Wall -o ../bin/launch launch.c -l_simpleloader
	export LD_LIBRARY_PATH=../bin/
#Provide the command for cleanup
